### ISSUE TITLE
lucide pack

### ISSUE THREAD

**Issue by danijerez** [kyleherzog/Blazicons#5]
It is an interesting project, will you add more icon packs in the future? for example
https://lucide.dev

**Comment by kyleherzog** [comment]
I wasn't familiar with Lucide until now. It appears to be a quality icon pack. Adding support for Lucide looks feasible.  The key factor is that there is a GitHub repo with all of the .svg files for the icons available.  Looks like for Lucide that would be here: https://github.com/lucide-icons/lucide.

**Comment by danijerez** [comment]
This is also interesting, it would be great to have them unified.
https://github.com/devicons/devicon

**Comment by kyleherzog** [comment]
A Lucide version has been released (https://www.nuget.org/packages/Blazicons.Lucide) as well as a Devicon version(https://www.nuget.org/packages/Blazicons.Devicon). Thanks for the suggestions.
