### ISSUE TITLE
Example user configurable icon

### ISSUE THREAD

**Issue by malessainray** [kyleherzog/Blazicons#7]
I'm curious how the intended way to use this library for user configurable icons would be. It's not about the user adding new icons to the collection of icons but rather picking one from the installed icon libraries for some user created entity in the application. 
On one hand something like an enumerable of all available icons with a user friendly name to search by and on the other hand, what would be persisted and passed to Blazicons component to render the correct icon the user chose? Do you by chance have a conceptual example on hand?

**Comment by kyleherzog** [comment]
I think what you are describing is pretty close to how the various Blazicons icon libraries are setup.  Each is setup as a static class with static properties. One property for each icon.
```csharp
public static class MyIcons
{
// the attribute set can be shared by SvgIcon objects
private static readonly ReadOnlyDictionary<string, string> attributeSet0 = new(new Dictionary<string, string>() {{"width", "400"}, {"height", "210"}, {"viewBox", "0 0 400 210"}, {"fill", "none"}, });

public static SvgIcon Triangle=> SvgIcon.FromContent("<path d='M150 5 L75 200 L225 200 Z' fill='currentColor'/>", attributeSet0);
}
```
You could certainly map these to something user facing that could be selectable by users.  For the [demo site](https://blazicons.com), we use reflection to enumerate all the SvgIcon objects in a given class. When a user clicks on an icon in the UI, we open a dialog with a Blazicon that has the Svg property bound to a property that holds the currently selected svg.

```html
<Blazicon Svg='ActiveIcon.Icon'></Blazicon>
```
